#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config split_ratio 0.61803
bspc config border_width 0
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config presel_feedback_color "#7c6f64"

bspc rule -a feh state=floating
bspc rule -a mpv state=floating
